package entidades;
// Generated 27 feb 2022 12:31:33 by Hibernate Tools 5.6.3.Final

import java.math.BigDecimal;

/**
 * DetalleIngreso generated by hbm2java
 */
public class DetalleIngreso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6511274769960479651L;
	private int iddetalleIngreso;
	private Articulo articulo;
	private Ingreso ingreso;
	private int cantidad;
	private BigDecimal precio;

	public DetalleIngreso() {
	}

	public DetalleIngreso(int iddetalleIngreso, Articulo articulo, Ingreso ingreso, int cantidad, BigDecimal precio) {
		this.iddetalleIngreso = iddetalleIngreso;
		this.articulo = articulo;
		this.ingreso = ingreso;
		this.cantidad = cantidad;
		this.precio = precio;
	}

	public int getIddetalleIngreso() {
		return this.iddetalleIngreso;
	}

	public void setIddetalleIngreso(int iddetalleIngreso) {
		this.iddetalleIngreso = iddetalleIngreso;
	}

	public Articulo getArticulo() {
		return this.articulo;
	}

	public void setArticulo(Articulo articulo) {
		this.articulo = articulo;
	}

	public Ingreso getIngreso() {
		return this.ingreso;
	}

	public void setIngreso(Ingreso ingreso) {
		this.ingreso = ingreso;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

}
