package entidades;
// Generated 27 feb 2022 12:31:33 by Hibernate Tools 5.6.3.Final

import java.math.BigDecimal;

/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6788657087556692756L;
	private int iddetalleVenta;
	private Articulo articulo;
	private Venta venta;
	private int cantidad;
	private BigDecimal precio;
	private BigDecimal descuento;

	public DetalleVenta() {
	}

	public DetalleVenta(int iddetalleVenta, Articulo articulo, Venta venta, int cantidad, BigDecimal precio,
			BigDecimal descuento) {
		this.iddetalleVenta = iddetalleVenta;
		this.articulo = articulo;
		this.venta = venta;
		this.cantidad = cantidad;
		this.precio = precio;
		this.descuento = descuento;
	}

	public int getIddetalleVenta() {
		return this.iddetalleVenta;
	}

	public void setIddetalleVenta(int iddetalleVenta) {
		this.iddetalleVenta = iddetalleVenta;
	}

	public Articulo getArticulo() {
		return this.articulo;
	}

	public void setArticulo(Articulo articulo) {
		this.articulo = articulo;
	}

	public Venta getVenta() {
		return this.venta;
	}

	public void setVenta(Venta venta) {
		this.venta = venta;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public BigDecimal getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigDecimal descuento) {
		this.descuento = descuento;
	}

}
