package entidades;
// Generated 27 feb 2022 12:31:33 by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6319629427792175734L;
	private int idpersona;
	private String tipoPersona;
	private String nombre;
	private String tipoDocumento;
	private String numDocumento;
	private String direccion;
	private String telefono;
	private String email;
	private Set<?> ventas = new HashSet<Object>(0);
	private Set<?> ingresos = new HashSet<Object>(0);

	public Persona() {
	}

	public Persona(int idpersona, String tipoPersona, String nombre) {
		this.idpersona = idpersona;
		this.tipoPersona = tipoPersona;
		this.nombre = nombre;
	}

	public Persona(int idpersona, String tipoPersona, String nombre, String tipoDocumento, String numDocumento,
			String direccion, String telefono, String email, Set<?> ventas, Set<?> ingresos) {
		this.idpersona = idpersona;
		this.tipoPersona = tipoPersona;
		this.nombre = nombre;
		this.tipoDocumento = tipoDocumento;
		this.numDocumento = numDocumento;
		this.direccion = direccion;
		this.telefono = telefono;
		this.email = email;
		this.ventas = ventas;
		this.ingresos = ingresos;
	}

	public int getIdpersona() {
		return this.idpersona;
	}

	public void setIdpersona(int idpersona) {
		this.idpersona = idpersona;
	}

	public String getTipoPersona() {
		return this.tipoPersona;
	}

	public void setTipoPersona(String tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public String getNumDocumento() {
		return this.numDocumento;
	}

	public void setNumDocumento(String numDocumento) {
		this.numDocumento = numDocumento;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set<?> getVentas() {
		return this.ventas;
	}

	public void setVentas(Set<?> ventas) {
		this.ventas = ventas;
	}

	public Set<?> getIngresos() {
		return this.ingresos;
	}

	public void setIngresos(Set<?> ingresos) {
		this.ingresos = ingresos;
	}

}
