package entidades;
// Generated 27 feb 2022 12:31:33 by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2730041084346452778L;
	private int idrol;
	private String nombre;
	private String descripcion;
	private Boolean estado;
	private Set<?> usuarios = new HashSet<Object>(0);

	public Rol() {
	}

	public Rol(int idrol, String nombre) {
		this.idrol = idrol;
		this.nombre = nombre;
	}

	public Rol(int idrol, String nombre, String descripcion, Boolean estado, Set<?> usuarios) {
		this.idrol = idrol;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
		this.usuarios = usuarios;
	}

	public int getIdrol() {
		return this.idrol;
	}

	public void setIdrol(int idrol) {
		this.idrol = idrol;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	public Set<?> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<?> usuarios) {
		this.usuarios = usuarios;
	}

}
