package entidades;
// Generated 27 feb 2022 12:31:33 by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8148839644108622271L;
	private int idusuario;
	private Rol rol;
	private String nombre;
	private String tipoDocumento;
	private String numDocumento;
	private String direccion;
	private String telefono;
	private String email;
	private String passwd;
	private Boolean estado;
	private Set<?> ventas = new HashSet<Object>(0);
	private Set<?> ingresos = new HashSet<Object>(0);

	public Usuario() {
	}

	public Usuario(int idusuario, Rol rol, String nombre, String email, String passwd) {
		this.idusuario = idusuario;
		this.rol = rol;
		this.nombre = nombre;
		this.email = email;
		this.passwd = passwd;
	}

	public Usuario(int idusuario, Rol rol, String nombre, String tipoDocumento, String numDocumento, String direccion,
			String telefono, String email, String passwd, Boolean estado, Set<?> ventas, Set<?> ingresos) {
		this.idusuario = idusuario;
		this.rol = rol;
		this.nombre = nombre;
		this.tipoDocumento = tipoDocumento;
		this.numDocumento = numDocumento;
		this.direccion = direccion;
		this.telefono = telefono;
		this.email = email;
		this.passwd = passwd;
		this.estado = estado;
		this.ventas = ventas;
		this.ingresos = ingresos;
	}

	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public String getNumDocumento() {
		return this.numDocumento;
	}

	public void setNumDocumento(String numDocumento) {
		this.numDocumento = numDocumento;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String string) {
		this.passwd = string;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	public Set<?> getVentas() {
		return this.ventas;
	}

	public void setVentas(Set<?> ventas) {
		this.ventas = ventas;
	}

	public Set<?> getIngresos() {
		return this.ingresos;
	}

	public void setIngresos(Set<?> ingresos) {
		this.ingresos = ingresos;
	}

}
