package entidades;
// Generated 27 feb 2022 12:31:33 by Hibernate Tools 5.6.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7519083172595406784L;
	private int idventa;
	private Persona persona;
	private Usuario usuario;
	private String tipoComprobante;
	private String serieComprobante;
	private String numComprobante;
	private Date fechaHora;
	private BigDecimal impuesto;
	private BigDecimal total;
	private String estado;
	private Set<?> detalleVentas = new HashSet<Object>(0);

	public Venta() {
	}

	public Venta(int idventa, Persona persona, Usuario usuario, String tipoComprobante, String numComprobante,
			Date fechaHora, BigDecimal impuesto, BigDecimal total, String estado) {
		this.idventa = idventa;
		this.persona = persona;
		this.usuario = usuario;
		this.tipoComprobante = tipoComprobante;
		this.numComprobante = numComprobante;
		this.fechaHora = fechaHora;
		this.impuesto = impuesto;
		this.total = total;
		this.estado = estado;
	}

	public Venta(int idventa, Persona persona, Usuario usuario, String tipoComprobante, String serieComprobante,
			String numComprobante, Date fechaHora, BigDecimal impuesto, BigDecimal total, String estado,
			Set<?> detalleVentas) {
		this.idventa = idventa;
		this.persona = persona;
		this.usuario = usuario;
		this.tipoComprobante = tipoComprobante;
		this.serieComprobante = serieComprobante;
		this.numComprobante = numComprobante;
		this.fechaHora = fechaHora;
		this.impuesto = impuesto;
		this.total = total;
		this.estado = estado;
		this.detalleVentas = detalleVentas;
	}

	public int getIdventa() {
		return this.idventa;
	}

	public void setIdventa(int idventa) {
		this.idventa = idventa;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getTipoComprobante() {
		return this.tipoComprobante;
	}

	public void setTipoComprobante(String tipoComprobante) {
		this.tipoComprobante = tipoComprobante;
	}

	public String getSerieComprobante() {
		return this.serieComprobante;
	}

	public void setSerieComprobante(String serieComprobante) {
		this.serieComprobante = serieComprobante;
	}

	public String getNumComprobante() {
		return this.numComprobante;
	}

	public void setNumComprobante(String numComprobante) {
		this.numComprobante = numComprobante;
	}

	public Date getFechaHora() {
		return this.fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}

	public BigDecimal getImpuesto() {
		return this.impuesto;
	}

	public void setImpuesto(BigDecimal impuesto) {
		this.impuesto = impuesto;
	}

	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set<?> getDetalleVentas() {
		return this.detalleVentas;
	}

	public void setDetalleVentas(Set<?> detalleVentas) {
		this.detalleVentas = detalleVentas;
	}

}
