package controladores;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.event.Event;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javafx.stage.Window;
import javafx.scene.control.CheckBox;

public class AccesoriosController {
	@FXML
	private CheckBox cBolsa;
	@FXML
	private CheckBox cGorra;
	@FXML
	private CheckBox cMochila;
	@FXML
	private CheckBox cMorral;
	@FXML
	private CheckBox cCaballero;
	@FXML
	private CheckBox cDama;
	@FXML
	private CheckBox cNinio;
	@FXML
	private CheckBox cNinia;
	@FXML
	private CheckBox cAdidas;
	@FXML
	private CheckBox cNike;
	@FXML
	private CheckBox cPuma;
	@FXML
	private CheckBox cFlexi;
	@FXML
	private CheckBox cKswiss;
	@FXML
	private CheckBox cLevi;
	@FXML
	private CheckBox cLotto;
	@FXML
	private CheckBox cNatural;
	@FXML
	private CheckBox c300;
	@FXML
	private CheckBox c600;
	@FXML
	private CheckBox c900;
	@FXML
	private CheckBox c1000;
	@FXML
	private Button volver;
	@FXML
	private ImageView A31;
	@FXML
	private ImageView A32;
	@FXML
	private ImageView A33;
	@FXML
	private ImageView A34;
	@FXML
	private ImageView A35;
	@FXML
	private ImageView A36;
	@FXML
	private ImageView A37;
	@FXML
	private ImageView A38;
	@FXML
	private ImageView A39;
	@FXML
	private ImageView A40;
	@FXML
	private ImageView A41;
	@FXML
	private ImageView A42;
	@FXML
	private ImageView A43;
	@FXML
	private ImageView A44;
	@FXML
	private ImageView A45;

	// Event Listener on CheckBox[#cBolsa].onAction
	@FXML
	public void soloBolsa(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cGorra].onAction
	@FXML
	public void soloGorra(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cMochila].onAction
	@FXML
	public void soloMochila(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cMorral].onAction
	@FXML
	public void soloMorral(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cCaballero].onAction
	@FXML
	public void soloCaballero(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cDama].onAction
	@FXML
	public void soloDama(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cNinio].onAction
	@FXML
	public void soloNinio(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cNinia].onAction
	@FXML
	public void soloNinia(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cAdidas].onAction
	@FXML
	public void soloAdidas(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cNike].onAction
	@FXML
	public void soloNike(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cPuma].onAction
	@FXML
	public void soloPuma(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cFlexi].onAction
	@FXML
	public void soloFlexi(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cKswiss].onAction
	@FXML
	public void soloKswiss(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cLevi].onAction
	@FXML
	public void soloLevi(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cLotto].onAction
	@FXML
	public void soloLotto(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cNatural].onAction
	@FXML
	public void soloNatural(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#c300].onAction
	@FXML
	public void solo300(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#c600].onAction
	@FXML
	public void solo600(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#c900].onAction
	@FXML
	public void solo900(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#c1000].onAction
	@FXML
	public void solo1000(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#volver].onAction
	@FXML
	public void presionaVolver(ActionEvent event) {
		try {
			loadStage("/vista/Menu.fxml", event);
		} catch (Exception ex) {
			System.out.println(ex);
		}
	}
	// Event Listener on ImageView[#A32].onMouseClicked
	@FXML
	public void presionaA32(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#A33].onMouseClicked
	@FXML
	public void presionaA33(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#A34].onMouseClicked
	@FXML
	public void presionaA34(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#A35].onMouseClicked
	@FXML
	public void presionaA35(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#A36].onMouseClicked
	@FXML
	public void presionaA36(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#A37].onMouseClicked
	@FXML
	public void presionaA37(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#A38].onMouseClicked
	@FXML
	public void presionaA38(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#A39].onMouseClicked
	@FXML
	public void presionaA39(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#A40].onMouseClicked
	@FXML
	public void presionaA40(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#A41].onMouseClicked
	@FXML
	public void presionaA41(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#A42].onMouseClicked
	@FXML
	public void presionaA42(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#A43].onMouseClicked
	@FXML
	public void presionaA43(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#A44].onMouseClicked
	@FXML
	public void presionaA44(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#A45].onMouseClicked
	@FXML
	public void presionaA45(MouseEvent event) {
		// TODO Autogenerated
	}
	private void loadStage(String URL, Event event) {
		try {
			// ((Node) (event.getSource())).getScene().getWindow().hide();

			Object eventSource = event.getSource();
			Node sourceAsNode = (Node) eventSource;
			Scene viejaEscena = sourceAsNode.getScene();
			Window ventana = viejaEscena.getWindow();
			Stage stage = (Stage) ventana;

			BorderPane root = (BorderPane) FXMLLoader.load(getClass().getResource(URL));
			Scene escena = new Scene(root);
			stage.centerOnScreen();
			stage.setScene(escena);
		} catch (IOException e) {
			// TODO: handle exception
			// Logger.getLogger(loginController.class.getName()).log(Level.SEVERE, null, e);
		}
	}
}
