package controladores;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Menu;
import javafx.scene.control.TextField;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.event.Event;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuItem;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.HBox;
import javafx.stage.Stage;
import javafx.stage.Window;
import javafx.scene.control.ScrollBar;
import javafx.scene.control.SplitPane;
import javafx.scene.control.Pagination;

public class MenuController implements Initializable {
	@FXML
	private TextField campoBusqueda;
	@FXML
	private Button buscarBoton;
	@FXML
	private Button sesionBoton;
	@FXML
	private MenuBar menu;
	@FXML
	private ImageView sesionImagen;
	@FXML
	private ImageView facebook;
	@FXML
	private ImageView instagram;
	@FXML
	private ImageView whatsapp;
	@FXML
	private ImageView youtube;
	@FXML
	private ScrollBar scroll;
	@FXML
	private ImageView image1;
	@FXML
	private ImageView image2;
	@FXML
	private ImageView image3;
	@FXML
	private ImageView image4;
	@FXML
	private ImageView image5;
	@FXML
	private ImageView image6;
	@FXML
	private ImageView image7;
	@FXML
	private Pagination pagina;

	// Event Listener on Button[#buscarBoton].onAction
	@FXML
	public void buscar(ActionEvent event) {
		// TODO Autogenerated
		
	}

	// Event Listener on Button[#sesionBoton].onAction
	@FXML
	public void iniciarSesion(ActionEvent event) {
		loadStage("/vista/Login.fxml",event);

	}

	// Event Listener on ImageView[#sesionImagen].onMouseClicked
	@FXML
	public void presionaImageSesion(MouseEvent event) {

	}

	// Event Listener on ImageView[#facebook].onMouseClicked
	@FXML
	public void presionaFacebook(MouseEvent event) {
		// TODO Autogenerated
		
	}

	// Event Listener on ImageView[#instagram].onMouseClicked
	@FXML
	public void presionaInstagram(MouseEvent event) {
		// TODO Autogenerated
		
	}

	// Event Listener on ImageView[#whatsapp].onMouseClicked
	@FXML
	public void presionaWhatsapp(MouseEvent event) {
		// TODO Autogenerated
		
	}

	// Event Listener on ImageView[#youtube].onMouseClicked
	@FXML
	public void presionaYoutube(MouseEvent event) {
		// TODO Autogenerated
		
	}

	// Event Listener on ImageView[#image1].onMouseClicked
	@FXML
	public void onClickImage(MouseEvent event) {
		// TODO Autogenerated
	
	}

	// Event Listener on ImageView[#image2].onMouseClicked
	@FXML
	public void presionaImage2(MouseEvent event) {
		// TODO Autogenerated
		
	}

	// Event Listener on ImageView[#image3].onMouseClicked
	@FXML
	public void presionaImage3(MouseEvent event) {
		// TODO Autogenerated
		
	}

	// Event Listener on ImageView[#image4].onMouseClicked
	@FXML
	public void presionaImage4(MouseEvent event) {
		// TODO Autogenerated
		
	}

	// Event Listener on ImageView[#image5].onMouseClicked
	@FXML
	public void presionaImage5(MouseEvent event) {
		// TODO Autogenerated
		
	}

	// Event Listener on ImageView[#image6].onMouseClicked
	@FXML
	public void presionaImage6(MouseEvent event) {
		// TODO Autogenerated
		
	}

	// Event Listener on ImageView[#image7].onMouseClicked
	@FXML
	public void presionaImage7(MouseEvent event) {
		// TODO Autogenerated
		
	}

	@FXML
	public void presionarPagina(MouseEvent event) throws FileNotFoundException {
		int pagindex = pagina.currentPageIndexProperty().intValue() + 1;
		File file;
		System.out.println(pagindex);
		switch (pagindex) {
		case 1:
			file = new File("src/imagenes/banner.jpg");
			InputStream imagen = (InputStream) new FileInputStream(file);
			image7.setImage(new Image(imagen));
			break;
		case 2:
			file = new File("src/imagenes/spring.jpg");
			InputStream imagen2 = (InputStream) new FileInputStream(file);
			image7.setImage(new Image(imagen2));
			break;
		case 3:
			file = new File("src/imagenes/banner6.jpg");
			InputStream imagen3 = (InputStream) new FileInputStream(file);
			image7.setImage(new Image(imagen3));
			break;
		case 4:
			file = new File("src/imagenes/anuncio.jpg");
			InputStream imagen4 = (InputStream) new FileInputStream(file);
			image7.setImage(new Image(imagen4));
			break;
		case 5:
			file = new File("src/imagenes/banner5.jpg");
			InputStream imagen5 = (InputStream) new FileInputStream(file);
			image7.setImage(new Image(imagen5));
			break;
		default:
			file = new File("src/imagenes/banner6.jpg");
			InputStream imagen6 = (InputStream) new FileInputStream(file);
			image7.setImage(new Image(imagen6));
			break;
		}

	}

	@FXML
	public void presionaMenu(MouseEvent event) {

	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		menu.getMenus().removeAll(menu.getMenus());
		Menu catalogos = new Menu("Catalogos");
		Menu zapatos = new Menu("Zapatos");
		Menu ropa = new Menu("Ropa");
		Menu ofertas = new Menu("Ofertas");
		Menu marcas = new Menu("Marcas");
		Menu accesorios = new Menu("Accesorios");
		menu.getMenus().add(catalogos);
		menu.getMenus().add(zapatos);
		menu.getMenus().add(ropa);
		menu.getMenus().add(ofertas);
		menu.getMenus().add(marcas);
		menu.getMenus().add(accesorios);
		MenuItem Hombre = new MenuItem("Hombre");
		MenuItem Mujer = new MenuItem("Mujer");
		MenuItem Caballero = new MenuItem("Caballero");
		MenuItem Dama = new MenuItem("Dama");
		MenuItem ninio = new MenuItem("Niño");
		MenuItem ninia = new MenuItem("Niña");
		MenuItem Adidas = new MenuItem("Adidas");
		MenuItem Charly = new MenuItem("Charly");
		MenuItem Converse = new MenuItem("Converse");
		MenuItem Flexi = new MenuItem("Flexi");
		MenuItem Jeep = new MenuItem("Jeep");
		MenuItem Lotto = new MenuItem("Lotto");
		MenuItem Nike = new MenuItem("Nike");
		MenuItem PriceS = new MenuItem("Price Shoes");
		MenuItem Jeans = new MenuItem("Jeans");
		MenuItem Playera = new MenuItem("Playera");
		MenuItem Sudadera = new MenuItem("Sudadera");
		MenuItem Blusa = new MenuItem("Blusa");

		zapatos.getItems().add(Hombre);
		zapatos.getItems().add(Mujer);
		zapatos.getItems().add(ninio);
		zapatos.getItems().add(ninia);
		marcas.getItems().add(Adidas);
		marcas.getItems().add(Charly);
		marcas.getItems().add(Converse);
		marcas.getItems().add(Flexi);
		marcas.getItems().add(Jeep);
		marcas.getItems().add(Lotto);
		marcas.getItems().add(Nike);
		marcas.getItems().add(PriceS);
		ropa.getItems().add(Jeans);
		ropa.getItems().add(Playera);
		ropa.getItems().add(Sudadera);
		ropa.getItems().add(Blusa);
		accesorios.getItems().add(Caballero);
		accesorios.getItems().add(Dama);

		Caballero.setOnAction(e -> {
			try {

				loadStage("/vista/Accesorios.fxml");
			} catch (Exception ex) {
				System.out.println(ex);
			}
		});
		Dama.setOnAction(e -> {
			try {

				loadStage("/vista/Accesorios.fxml");
			} catch (Exception ex) {
				System.out.println(ex);
			}
		});
		Hombre.setOnAction(e -> {
			try {
				loadStage("/vista/Zapatos.fxml");
			} catch (Exception ex) {
				System.out.println(ex);
			}

		});

		Mujer.setOnAction(e -> {
			try {
				loadStage("/vista/Zapatos.fxml");
			} catch (Exception ex) {
				System.out.println(ex);
			}

		});
		ninio.setOnAction(e -> {
			try {
				loadStage("/vista/Zapatos.fxml");
			} catch (Exception ex) {
				System.out.println(ex);
			}

		});
		ninia.setOnAction(e -> {
			try {
				loadStage("/vista/Zapatos.fxml");
			} catch (Exception ex) {
				System.out.println(ex);
			}

		});
		Jeans.setOnAction(e -> {
			try {
				loadStage("/vista/Ropa.fxml");
			} catch (Exception ex) {
				System.out.println(ex);
			}
		});
		Playera.setOnAction(e -> {
			try {
				loadStage("/vista/Ropa.fxml");
			} catch (Exception ex) {
				System.out.println(ex);
			}
		});
		Sudadera.setOnAction(e -> {
			try {
				loadStage("/vista/Ropa.fxml");
			} catch (Exception ex) {
				System.out.println(ex);
			}
		});
		Blusa.setOnAction(e -> {
			try {
				loadStage("/vista/Ropa.fxml");
			} catch (Exception ex) {
				System.out.println(ex);
			}
		});
	}

	private void loadStage(String URL) {
		try {
			Stage stage = (Stage) menu.getScene().getWindow();

			SplitPane root = (SplitPane) FXMLLoader.load(getClass().getResource(URL));
			Scene escena = new Scene(root);
			stage.centerOnScreen();
			stage.setScene(escena);
		} catch (Exception e) {
			// TODO: handle exception
			// Logger.getLogger(loginController.class.getName()).log(Level.SEVERE, null, e);
		}
	}
	private void loadStage(String URL, Event event) {
		try {
			// ((Node) (event.getSource())).getScene().getWindow().hide();

			Object eventSource = event.getSource();
			Node sourceAsNode = (Node) eventSource;
			Scene viejaEscena = sourceAsNode.getScene();
			Window ventana = viejaEscena.getWindow();
			Stage stage = (Stage) ventana;

			HBox root = (HBox) FXMLLoader.load(getClass().getResource(URL));
			Scene escena = new Scene(root);
			stage.centerOnScreen();
			stage.setScene(escena);
		} catch (IOException e) {
			// TODO: handle exception
			// Logger.getLogger(loginController.class.getName()).log(Level.SEVERE, null, e);
		}
	}
}
