package controladores;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javafx.stage.Window;

public class PaginaVendedorController {
	@FXML
	private Button botonPedidos;
	@FXML
	private Button Rastrear;
	@FXML
	private Button botonFactura;
	@FXML
	private Button InformacionCuenta;
	@FXML
	private Button volver;
	@FXML
	private Label privacidad;
	@FXML
	private Label terminos;
	@FXML
	private Label email;
	@FXML
	private Label nombre;
	@FXML
	private Label direccion;
	@FXML
	private Label telefono;

	// Event Listener on Button[#botonPedidos].onAction
	@FXML
	public void presionaPedidos(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#Rastrear].onAction
	@FXML
	public void presionaRastrear(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#botonFactura].onAction
	@FXML
	public void presionaFactura(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#InformacionCuenta].onAction
	@FXML
	public void presionaDatos(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#volver].onAction
	@FXML
	public void presionaVolver(ActionEvent event) {
		// TODO Autogenerated
		loadStage("/vista/Menu.fxml", event);
	}

	private void loadStage(String string, ActionEvent event) {

		try {
			Object eventSource = event.getSource();
			Node sourceAsNode = (Node) eventSource;
			Scene viejaEscena = sourceAsNode.getScene();
			Window ventana = viejaEscena.getWindow();
			Stage stage = (Stage) ventana;

			BorderPane root = (BorderPane) FXMLLoader.load(getClass().getResource(string));
			Scene escena = new Scene(root);
			stage.centerOnScreen();
			stage.setScene(escena);

		} catch (Exception e) {
			

		}
		
	}

	// Event Listener on Label[#privacidad].onMouseClicked
	@FXML
	public void presionaPrivacidad(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Label[#terminos].onMouseClicked
	@FXML
	public void presionaTerminos(MouseEvent event) {
	}
}
