package controladores;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.event.ActionEvent;
import javafx.event.Event;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javafx.stage.Window;

public class PruebaController {
	@FXML
	private Button a;
	@FXML
	private Button b;
	@FXML
	private Button c;
	@FXML
	private Button d;
	@FXML
	private BorderPane BPane;

	// Event Listener on Button[#a].onAction
	@FXML
	public void pusha(ActionEvent event) {
		// TODO Autogenerated
		loadStage("/vista/Menu.fxml", event);
	}
	// Event Listener on Button[#b].onAction
	@FXML
	public void pushb(ActionEvent event) {
		// TODO Autogenerated
		loadStage("/vista/Login.fxml", event);
	}
	// Event Listener on Button[#c].onAction
	@FXML
	public void pushc(ActionEvent event) {
		// TODO Autogenerated
		loadStage("/vista/PaginaUsuario.fxml", event);
	}
	// Event Listener on Button[#d].onAction
	@FXML
	public void pushd(ActionEvent event) {
		// TODO Autogenerated
		loadStage("/vista/RegistrarUsuario.fxml", event);
	}
	private void loadStage(String URL, Event event) {
		try {
			Object eventSource = event.getSource();
			Node sourceAsNode = (Node) eventSource;
			Scene viejaEscena = sourceAsNode.getScene();
			Window ventana = viejaEscena.getWindow();
			Stage stage = (Stage) ventana;

			BorderPane root = (BorderPane) FXMLLoader.load(getClass().getResource(URL));
			Scene escena = new Scene(root);
			stage.centerOnScreen();
			stage.setScene(escena);

		} catch (Exception e) {
			// TODO: handle exception2

		}
	}
}
