package controladores;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.event.Event;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javafx.stage.Window;
import javafx.scene.control.CheckBox;

public class ZapatosController {
	@FXML
	private CheckBox cBota;
	@FXML
	private CheckBox cChoclo;
	@FXML
	private CheckBox cConfort;
	@FXML
	private CheckBox cCaballero;
	@FXML
	private CheckBox cDama;
	@FXML
	private CheckBox cNinio;
	@FXML
	private CheckBox cNinia;
	@FXML
	private CheckBox cAdidas;
	@FXML
	private CheckBox cNke;
	@FXML
	private CheckBox cPuma;
	@FXML
	private CheckBox cFlexi;
	@FXML
	private CheckBox cKswiss;
	@FXML
	private CheckBox cLevi;
	@FXML
	private CheckBox cLotto;
	@FXML
	private CheckBox cNatural;
	@FXML
	private CheckBox c300;
	@FXML
	private CheckBox c600;
	@FXML
	private CheckBox c900;
	@FXML
	private CheckBox c1000;
	@FXML
	private Button volver;
	@FXML
	private ImageView Z1;
	@FXML
	private ImageView Z2;
	@FXML
	private ImageView Z3;
	@FXML
	private ImageView Z4;
	@FXML
	private ImageView Z5;
	@FXML
	private ImageView Z6;
	@FXML
	private ImageView Z7;
	@FXML
	private ImageView Z8;
	@FXML
	private ImageView Z9;
	@FXML
	private ImageView Z10;
	@FXML
	private ImageView Z11;
	@FXML
	private ImageView Z12;
	@FXML
	private ImageView Z13;
	@FXML
	private ImageView Z14;
	@FXML
	private ImageView Z15;

	// Event Listener on CheckBox[#cBota].onAction
	@FXML
	public void soloBota(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cChoclo].onAction
	@FXML
	public void soloChoclo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cConfort].onAction
	@FXML
	public void soloConfort(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cCaballero].onAction
	@FXML
	public void soloCaballero(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cDama].onAction
	@FXML
	public void soloDama(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cNinio].onAction
	@FXML
	public void soloNinio(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cNinia].onAction
	@FXML
	public void soloNinia(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cAdidas].onAction
	@FXML
	public void soloAdidas(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cNke].onAction
	@FXML
	public void soloNike(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cPuma].onAction
	@FXML
	public void soloPuma(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cFlexi].onAction
	@FXML
	public void soloFlexi(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cKswiss].onAction
	@FXML
	public void soloKswiss(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cLevi].onAction
	@FXML
	public void soloLevi(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cLotto].onAction
	@FXML
	public void soloLotto(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#cNatural].onAction
	@FXML
	public void soloNatural(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#c300].onAction
	@FXML
	public void solo300(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#c600].onAction
	@FXML
	public void solo600(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#c900].onAction
	@FXML
	public void solo900(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#c1000].onAction
	@FXML
	public void solo1000(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#volver].onAction
	@FXML
	public void presionaVolver(ActionEvent event) {
		try {
			loadStage("/vista/Menu.fxml", event);
		} catch (Exception ex) {
			System.out.println(ex);
		}
	}
	// Event Listener on ImageView[#Z1].onMouseClicked
	@FXML
	public void presionaZ1(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#Z2].onMouseClicked
	@FXML
	public void presionaZ2(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#Z3].onMouseClicked
	@FXML
	public void presionaZ3(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#Z4].onMouseClicked
	@FXML
	public void presionaZ4(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#Z5].onMouseClicked
	@FXML
	public void presionaZ5(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#Z6].onMouseClicked
	@FXML
	public void presionaZ6(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#Z7].onMouseClicked
	@FXML
	public void presionaZ7(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#Z8].onMouseClicked
	@FXML
	public void presionaZ8(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#Z9].onMouseClicked
	@FXML
	public void presionaZ9(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#Z10].onMouseClicked
	@FXML
	public void presionaZ10(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#Z11].onMouseClicked
	@FXML
	public void presionaZ11(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#Z12].onMouseClicked
	@FXML
	public void presionaZ12(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#Z13].onMouseClicked
	@FXML
	public void presionaZ13(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#Z14].onMouseClicked
	@FXML
	public void presionaZ14(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#Z15].onMouseClicked
	@FXML
	public void presionaZ15(MouseEvent event) {
		// TODO Autogenerated
	}
	private void loadStage(String URL, Event event) {
		try {
			// ((Node) (event.getSource())).getScene().getWindow().hide();

			Object eventSource = event.getSource();
			Node sourceAsNode = (Node) eventSource;
			Scene viejaEscena = sourceAsNode.getScene();
			Window ventana = viejaEscena.getWindow();
			Stage stage = (Stage) ventana;

			BorderPane root = (BorderPane) FXMLLoader.load(getClass().getResource(URL));
			Scene escena = new Scene(root);
			stage.centerOnScreen();
			stage.setScene(escena);
		} catch (IOException e) {
			// TODO: handle exception
			// Logger.getLogger(loginController.class.getName()).log(Level.SEVERE, null, e);
		}
	}
}
